### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by advphp** [LaraGuardiola/nodejs-dalai-alpaca-ai#1]
i ran the script, but it doesn't work, it just keeps loading.

screenshot
https://i.imgur.com/PT3QnZb.png

if you run dalai directly it works normally, but the problem seems to be in your software

**Comment by LaraGuardiola** [comment]
Hi, I'll need more information if you don't mind, try to open the dev tools and go to Network, everytime you send a message you are making a post request (like this /alpaca). In your terminal everything seems correct except that is not calling the model

**Comment by advphp** [comment]
I managed to solve the problem by changing the browser.

I have a few questions if you don't mind
1. I only have 7B, but it sets me to options 7B and 13B, why do the two options appear together?
2. How do I summon a llama?
3. Do you recommend working on Windows or Linux?

**Comment by LaraGuardiola** [comment]
1) that's on me, when I started I had the 2 models and I basically hardcoded the options lol. I'll fix that asap.
2) Llama never worked for me 💀 
3) Even though I'm using Windows these models use a lot of computing power and ram,  so the less bloated ur OS is, the better.

Glad you made It work.

**Comment by advphp** [comment]
Can I contact you via WhatsApp or Telegram, I can provide some solutions to operate the llama

I also have a server with good specifications, let's try to work on it
